### ISSUE TITLE
Variables declared with a generic type aren't remapped properly

### ISSUE THREAD

**Issue by pdinklag** [HeartPattern/MC-Remapper#3]
Cool little project! 😄 

I noticed that variables with a generic type lose their generic type. For example, in the `spawnLingeringCloud()` method of `net.minecraft.world.entity.monster.Creeper`, there's a `Collection<MobEffectInstance>`. After remapping, it's just a `Collection` (i.e., of `Object`), which makes re-compiling the class impossible because of a ranged `for` loop.

I don't know much about the ASM library, but I suppose this case could be detected and handled properly? I can't tell if only local variables are affected or if this is a general issue.

**Comment by HeartPattern** [comment]
Due to type erasure of java, generic information is removed in compile time. Moreover, Mojang remove local variable type attribute from byte code, there are no information about generic type.
[https://www.baeldung.com/java-type-erasure](url)
Also Mojang's mapping file does not contains generic type information, there is no way to automatically restore generic type.

**Comment by HeartPattern** [comment]
Did you run remapping with option --fixlocalvar=delete ?
This option remove local variable table which contains type information.
Running with --fixlocalvar=no or --fixlocalvar=rename will preserve generic information.

**Comment by pdinklag** [comment]
You're right, I ran it with `delete` and it works fine with `rename`, thanks!
